CC = gcc
CFLAGS = -Wall -Wextra -Werror -pedantic

odo_api_0: todo_api_0.c
	$(CC) $(CFLAGS) -o todo_api_0 todo_api_0.c

todo_api_1: todo_api_1.c
	$(CC) $(CFLAGS) -o todo_api_1 todo_api_1.c

todo_api_2: todo_api_2.c
	$(CC) $(CFLAGS) -o todo_api_2 todo_api_2.c

todo_api_3: todo_api_3.c
	$(CC) $(CFLAGS) -o todo_api_3 todo_api_3.c

todo_api_4: todo_api_4.c
	$(CC) $(CFLAGS) -o todo_api_4 todo_api_4.c

todo_api_5: todo_api_5.c
	$(CC) $(CFLAGS) -o todo_api_5 todo_api_5.c

clean:
	rm -f todo_api_0

